### ISSUE TITLE
Weird behaviour of CBC when solving TSP with lazy constraints

### ISSUE THREAD

**Issue by JeroenGar** [coin-or/python-mip#193] opened 2021-04-21 14:17 UTC
**Describe the bug**
I am trying to solve a TSP by adding lazy constraints to eliminate subtours, analogous to the `tsp-lazy-ulysses22.py` example. However, it seems that, in larger problems, CBC just keeps adding constraints until it eventually crashes with the following message:
`Process finished with exit code -1073740940 (0xC0000374)`

Gurobi, on the other hand, does not seem to have this problem.
For a random instance with 60 cities for example, Gurobi solves it in 0.23s and creates ~200 constraints while CBC crashes after adding over 3500 constraints.

Why does this happen? Am I doing something wrong?
I would not expect CBC to deliver the same performance as Gurobi, but this seems to be quite extreme.

**To Reproduce**
I slightly modified the `tsp-lazy-ulysses22.py` so it creates a random instance with a number of nodes.
Variable `n` defines the number of points and the solver is selected when creating the model object. 
In the example, CBC is used and an instance with 60 points is created. 
This leads to the behaviour described in the previous paragraph.

```python
"""Example of a Branch-and-Cut implementation for the Traveling Salesman
Problem. Initially an incomplete formulation including only the degree
constraints is created. Sub-tour elimination constraints are generated
on-demand using a CutsGenerator that performs a depth-first search to identify
disconnected sub-routes."""

from typing import Tuple, Set, List
from math import floor, cos, acos
from itertools import product
from collections import defaultdict
from random import seed, randint
from math import sqrt
from sys import stdout as out
from mip import Model, xsum, minimize, BINARY, ConstrsGenerator, CutPool


def subtour(N: Set, outa: defaultdict, node) -> List:
    """checks if a given node belongs to a disconnected sub-route and
    returns involved nodes"""
    queue = [node]
    visited = set(queue)
    while queue:
        n = queue.pop()
        for nl in outa[n]:
            if nl not in visited:
                queue.append(nl)
                visited.add(nl)

    if len(visited) != len(N):
        return list(visited)
    else:
        return []


class SubTourLazyGenerator(ConstrsGenerator):
    """generated sub-tour elimination constraints"""

    def __init__(self, xv):
        self._x = xv

    def generate_constrs(self, model: Model, depth: int = 0, npass: int = 0):
        x_, N, cp = model.translate(self._x), range(len(self._x)), CutPool()
        outa = [[j for j in N if x_[i][j].x >= 0.99] for i in N]

        for node in N:
            S = set(subtour(N, outa, node))
            if S:
                AS = [(i, j) for (i, j) in product(S, S) if i != j]
                cut = xsum(x_[i][j] for (i, j) in AS) <= len(S) - 1
                cp.add(cut)
        for cut in cp.cuts:
            model += cut

n = 60  # number of points
V = set(range(n))
seed(0)
p = [(randint(1, 100), randint(1, 100)) for i in V]  # coordinates
Arcs = [(i, j) for (i, j) in product(V, V) if i != j]

c = [[round(sqrt((p[i][0]-p[j][0])**2 + (p[i][1]-p[j][1])**2)) for j in V] for i in V]

model = Model(solver_name="CBC")

# binary variables indicating if arc (i,j) is used on the route or not
x = [[model.add_var(var_type=BINARY) for j in V] for i in V]

# objective function: minimize the distance
model.objective = minimize(xsum(c[i][j] * x[i][j] for i in V for j in V))

# constraint : leave each city only once
for i in V:
    model += xsum(x[i][j] for j in V - {i}) == 1

# constraint : enter each city only once
for i in V:
    model += xsum(x[j][i] for j in V - {i}) == 1

model.lazy_constrs_generator = SubTourLazyGenerator(x)

# optimizing
model.optimize(max_seconds=70)

# checking if a solution was found
if model.num_solutions:
    out.write(
        "route with total distance %g found: %s" % (model.objective_value, 0)
    )
    nc = 0
    while True:
        nc = [i for i in V if x[nc][i].x >= 0.99][0]
        out.write(" -> %s" % nc)
        if nc == 0:
            break
    out.write("\n")
```

**Expected behavior**
I would expect CBC to produce a solution. 

**Desktop**
 - Operating System, version: Windows 10 20H2
 - Python version: Python 3.9
 - Python-MIP version:  Python-MIP 1.13.0 (same behavior on 1.12 and 1.9.4)

**Additional context**
I can not use Gurobi for my use case. CBC is my only option. 
Any suggestions/help are very welcomed.

**Comment by JeroenGar** [comment] 2021-04-22 13:39
Running the example in Linux (WSL) gives some more information:
[log.txt](https://github.com/coin-or/python-mip/files/6358661/log.txt)

**Comment by christian2022** [comment] 2021-11-15 16:26
Please update. I cannot reproduce this behaviour with cbc from Mar 30 2021.

**Comment by JeroenGar** [comment] 2021-11-17 08:35
Hmmmm indeed, if i install the python-mip package directly from master branch it works correct.
I assume this is because new CBC binaries are included.

Can you also not reproduce it with the binaries that are included in Python-MIP 1.13.0?

**Comment by christian2022** [comment] 2021-11-17 08:51
Several fixes have been made in CBC and yours obviously got fixed.
Haven't tried with Python-MIP 1.13, just with what I have on my machine.

@h-g-s Due to the bug fixes in CBC, maybe it's time for a new release of Python-mip also?

**Comment by sebheger** [comment] 2022-06-22 14:47
Fixed by https://github.com/coin-or/python-mip/milestone/2

**Closed by sebheger** 2022-06-22 14:47 UTC
Labels: bug, cbc, not reproducible
