### ISSUE TITLE
Nondeterministic crash within cbc-c-windows-x86-64.dll

### ISSUE THREAD

**Issue by pgoelz** [coin-or/python-mip#75] opened 2020-03-23 17:36 UTC
We have been chasing a bug where CBC silently crashes and takes the entire program with it. The bug only appears on Windows and is not triggered by any specific ILP. Our usage case optimizes a fixed sequence of ILPs and will crash at a different ILP each time (I have verified that the ILPs are indeed the same). The cause seems to be an access violation within the call to `cbclib.Cbc_solve()` in `cbc-c-windows-x86-64.dll`, but I don’t know how to debug further.
I was hoping to recompile CBC with debug flags, but coinbrew fails with `checking how to get verbose linking output from ... configure: WARNING: compilation failed`. I also tried using your compilation scripts (`./downloadCBC.sh`, then `./buildCBCWin.sh`, on a linux machine), but got the following error output:

    ...
    checking whether to build static libraries... yes
    checking how to run the C++ preprocessor... /lib/cpp
    configure: error: in `/home/ec2-user/python-mip/scripts/Cbc':
    configure: error: C++ preprocessor "/lib/cpp" fails sanity check 
    See `config.log' for more details
    make: *** No targets specified and no makefile found.  Stop.
    make: *** No rule to make target `install'.  Stop.

I’m attaching [config.log](https://github.com/coin-or/python-mip/files/4366968/config.log). Am I using the scripts wrong? So far, I have not modified any flags.

I mentioned this issue in https://github.com/coin-or/python-mip/issues/70, and @tkralphs asked me to open a new issue. My compiler is gcc 7.3.1.

**Comment by tkralphs** [comment] 2020-03-23 18:39
The main problem is that you don't have the compiler installed. If you check config.log, you will see
```
./configure: line 4796: g++: command not found
```
But you are also doing by hand exactly what [coinbrew](https://github.com/coin-or/coinbrew) is designed to automate for you. You definitely do not need to provide all those arguments to configure and build each project separately. Just use `coinbrew`? It should work out of the box in MSys2 with MinGW compilers. Follow the steps are here

https://github.com/coin-or/python-mip/issues/75

I'm going to close this issue for now, but you can reopen if you have further problems. You may consider opening an issue in the [Cbc](https://github.com/coin-or/Cbc) or coinbrew projects, though, if the issue is with those projects and not this one.

**Closed by tkralphs** 2020-03-23 18:39 UTC

**Comment by pgoelz** [comment] 2020-03-23 22:50
Apologies, I did not realize that GCC did not by default include C++ tools on my test system. For future reference, installing C++ and Fortran support to GCC and then installing `lapack` made the coinbrew compilation succeed.

**Comment by tkralphs** [comment] 2020-03-23 23:15
Great, thanks for following up!
