### ISSUE TITLE
Objective Function .lp File Bug

### ISSUE THREAD

**Issue by ghost** [coin-or/python-mip#245] opened 2022-02-08 11:36 UTC
**Describe the bug**
Every time I save my model by creating a .lp file, although the code stays the exact same, the objective function in the .lp file changes. This means that if/when I externally solve the .lp file and try to use the solution (whether a .mst or .sol file) to MIPstart, the values are not accepted.

**To Reproduce**
I have written a write to .lp line, then a subsequent read .lp line, in order to demonstrate the bug. If I remove both lines, the code works flawlessly, showing an error in the .lp file and after further inspection, a scenario where the objective function constantly changes. [PythonMIPBug.zip](https://github.com/coin-or/python-mip/files/8023415/PythonMIPBug.zip)

**Expected behavior**
I expect that if I wrote then read a .lp file, that the objective function would stay the same, assuming the code itself too stayed the same.

**Desktop (please complete the following information):**
 - Operating System, version: Windows 10
 - Python version: Tried on 3.8/3.9/3.10
 - Python-MIP version (we recommend you to test with the latest version):  1.13.0

Thank you.

**Comment by sebheger** [comment] 2022-02-09 21:40
@Fonti1996 Thanks for reporting the issue. I can reproduce that there is something going wrong by running your script, but I need your help check where the problem is:

- please reduce the size of the example (e.g. less SC_Data).
- Could you replace all sets by sorting them into lists (maybe alphabetically), that we have deterministic runs to compare. At the moment I can't diff the output, because I get a permutated model at each run.

Thanks

**Comment by sebheger** [comment] 2022-05-09 11:49
Will close this issue as we cannot reproduce.

**Closed by sebheger** 2022-05-09 11:49 UTC
Labels: discarded
