### ISSUE TITLE
`0 - Var` returns wrong result

### ISSUE THREAD

**Issue by vang1ong7ang** [coin-or/python-mip#126] opened 2020-07-04 06:50 UTC
**Describe the bug**

`0 - Var` returns wrong result

**To Reproduce**
Steps to reproduce the behavior **please include attached any files needed to reproduce the error**. We can only help you if we can reproduce the error ourselves and debug.

```python
from mip import Model

m = Model()

x = m.add_var()
print(x)
y = 0 - x
print(y)
```

**Expected behavior**

expect output should be:

```
var(0)
- var(0)
```

but actually it is:

```
var(0)
var(0)
```

**Desktop (please complete the following information):**
 - Operating System, version: `Linux bd351c4cdf15 4.19.125-1.*****.*****.x86_64 #1 SMP Sat May 30 16:11:30 UTC 2020 x86_64 GNU/Linux`
 - Python version: `3.8.1`
 - Python-MIP version (we recommend you to test with the latest version):  `1.9.3`

**Additional context**

**Comment by vang1ong7ang** [comment] 2020-07-04 06:57
the problem should be here:

https://github.com/coin-or/python-mip/blob/a215205607bad484d57a6bc7cba0e3c75e64f3ed/mip/entities.py#L571-L572

**Comment by tuliotoffolo** [comment] 2020-07-11 21:06
Thank you very much for pointing this out! I believe the problem is fixed now!

**Closed by tuliotoffolo** 2020-07-11 21:06 UTC
