### ISSUE TITLE
Model.write() behaves differently with .lp and .mps formats

### ISSUE THREAD

**Issue by ryanjoneil** [coin-or/python-mip#299] opened 2022-08-02 15:14 UTC
**Describe the bug**

If I write the same model to two different files:

```py
m.write('foo.lp')
m.write('foo.mps')
```

I get two files with different characteristics:

* `foo.lp` is a text file in LP format.
* `foo.mps.mps.gz` is a gzipped MPS file with a repeated `.mps` extension.

**Expected behavior**

In the example above, I expect to get two files:

* `foo.lp` - text file in LP format
* `foo.mps` - text file in MPS format

I do not expect the `.mps.mps` repeated extension.

I only expect the output to be gzipped if I explicitly add a `.gz` extension the filename.

**Desktop (please complete the following information):**
 - Operating System, version: macOS 11.6.7 
 - Python version: 3.7.8
 - Python-MIP version (we recommend you to test with the latest version):  1.13.0

**Comment by rschwarz** [comment] 2022-08-03 07:30
I think the `model.write` method simply [delegates](https://github.com/coin-or/python-mip/blob/master/mip/model.py#L762) the call to the underlying solver (CBC or Gurobi), so the offending behavior is likely defined there.

**Comment by sebheger** [comment] 2022-08-03 10:56
@ryanjoneil  Thanks for reporting this. But, I will close this as it is a duplicate of #164

**Closed by sebheger** 2022-08-03 10:56 UTC

**Comment by ryanjoneil** [comment] 2022-08-03 15:47
I have some follow-up questions, but I will put those on #164.
