### ISSUE TITLE
name 'cbclib' is not defined version 1.8.2 (same issue as #37)

### ISSUE THREAD

**Issue by Gectrics** [coin-or/python-mip#103] opened 2020-05-20 18:10 UTC
Hello, 

I am having the same issue with the cbc library as issue #37 on an 10.13.6 MacBook (HIGH SIERRA) with MIP versions from 1.5.3 to 1.8.2 . Additionally, I also facing unstable behaviour with MIP versions from 1.5.0 to 1.5.2 (solution does not respect the constraints). 
 
Details of the error:
 
<img width="412" alt="issue_mip_cbc" src="https://user-images.githubusercontent.com/22730950/82481517-5566e000-9acd-11ea-84f4-79bf246cfbde.png">

Thank you for your help. 

Kind regards

Hugo

**Comment by tuliotoffolo** [comment] 2020-05-20 22:54
Hello Hugo,

Indeed many people are having trouble to use Python-MIP on MacOS. Tomorrow I’ll execute a set of experiments together with a contributor from Chile to sort this out. Hopefully, a solution will be committed very soon.
Em 20 de mai de 2020 15:11 -0300, Gectrics <notifications@github.com>, escreveu:

**Comment by tuliotoffolo** [comment] 2020-05-21 19:02
Hello again, Hugo!
Would you please try version 1.8.3 (it should be online in a few minutes)? @pabloazurduy helped me lot of this afternoon and it seems that the problem is solved now.

**Closed by tuliotoffolo** 2020-05-21 19:02 UTC

**Comment by Gectrics** [comment] 2020-05-22 16:33
Hello Túlio, 

It now works with MIP 1.9.0. 
Thank you 

Kind regards

Hugo

**Comment by tuliotoffolo** [comment] 2020-05-22 17:43
Excellent!  👍
